### ISSUE TITLE
Search does not work when [emojisToShowFilter] is used

### ISSUE THREAD

**Issue by multimike77** [TypeCtrl/ngx-emoji-mart#182]
When using the search bar in the picker, search always returns empty result when the picker is configured with [emojisToShowFilter].
When removing emojisToShowFilter, search works again as expected.

Reason might be in emoji-search-service.ts
`emojisToShowFilter(this.emojiService.names[result.id]),`
whereas it should rather be
`emojisToShowFilter(result.unified)`
as the filter is working with the unified codes and not names.

**Comment by multimike77** [comment]
Are there any updates on this one?

**Comment by s-moran** [comment]
> Are there any updates on this one?

I pushed up a fix for #172. The issue fixed there is probably similar to this one. I can take a look.

**Comment by scttcper** [comment]
thanks @s-moran for the two fixes, looks good 👍

**Comment by multimike77** [comment]
Problem is still there, as the change from #275  was reverted in https://github.com/TypeCtrl/ngx-emoji-mart/commit/498c24493fc3f09e19b220164186a9f503201e4c

**Comment by s-moran** [comment]
@scttcper do you know why this was reverted?

**Comment by scttcper** [comment]
because you can use any field in the emoji data
```ts
const emojisToShowFilter = (data: EmojiData) => {
	return data.unified !== '1F34D';
};
```
